name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false # prevent test to stop if one fails
      matrix:
        node-version: [16, 18, 20, 22] # match patched node versions
        os: [ubuntu-latest] # Skip macos-latest, windows-latest for now

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install deps
        run: yarn install --ignore-engines

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Check Patches
        run: ./scripts/test_patch.sh node${{ matrix.node-version }}
