name: Update expected sha256sums

on:
    workflow_dispatch:
        inputs:
            shas:
                description: 'Expected sha256sums. Format is "<sha> node-v<version>-<os>-<arch>"'
                required: true
                type: string
    workflow_call:
        inputs:
            shas:
                description: 'Expected sha256sums. Format is "<sha> node-v<version>-<os>-<arch>"'
                required: true
                type: string

jobs:
    update:
        permissions:
            contents: write
            pull-requests: write
        strategy:
            fail-fast: false # prevent test to stop if one fails
            matrix:
                node-version: [20] 
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: "yarn"
            
            - name: Install deps
              run: yarn install --ignore-engines

            - name: Parse and update shas.txt
              run: |
                # Write the shas input to a temporary file outside the repo
                tmp_file="/tmp/new-shas-${GITHUB_RUN_ID}.txt"
                echo "${{ inputs.shas }}" > "$tmp_file"
                # Build and run the TypeScript script
                yarn build
                node lib-es5/parse-update-shas.js "$tmp_file"
                # Clean up the temporary file
                rm "$tmp_file"
            - name: Update expected shas
              run: |
                yarn updateExpected
            
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                commit-message: "fix: update expected shas"
                title: "fix: update expected shas"
                body: "Update expected sha256sums for Node.js\n\n${{ inputs.shas }}"
                branch: "update-expected-shas-${{ github.run_id }}"
                base: "main"
                delete-branch: true
                labels: "chore, shas"
                draft: false